services:
  postgres:
    image: postgres:13
    container_name: guardian-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_MULTIPLE_DATABASES: airflow,guardian_dw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - guardian-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    networks:
      - guardian-net

  airflow-webserver:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile.airflow
    container_name: guardian-airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${SECRET_KEY}
      - POSTGRES_LOG_DB=guardian_dw
      - DBT_PROJECT_DIR=/opt/airflow/dbt
      - DBT_PROFILES_DIR=/opt/airflow/dbt/.dbt
      - DBT_SERVICE_NAME=dbt
      - PYTHONPATH=/opt/airflow
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - GUARDIAN_BASE_URL=${GUARDIAN_BASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=guardian_dw
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./dbt:/opt/airflow/dbt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - guardian-net

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile.airflow
    container_name: guardian-airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - DBT_PROJECT_DIR=/opt/airflow/dbt
      - DBT_PROFILES_DIR=/opt/airflow/dbt/.dbt
      - DBT_SERVICE_NAME=dbt
      - PYTHONPATH=/opt/airflow
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - GUARDIAN_BASE_URL=${GUARDIAN_BASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=guardian_dw
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./dbt:/opt/airflow/dbt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/data:/opt/airflow/data
    command: scheduler
    networks:
      - guardian-net

  loader:
    build:
      context: ./src
      dockerfile: Dockerfile.loader
    container_name: guardian-loader
    depends_on:
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=guardian_dw
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - PYTHONPATH=/app
    volumes:
      - ./src:/app
    networks:
      - guardian-net

  superset:
    build:
      context: ./docker
      dockerfile: Dockerfile.superset
    container_name: guardian-superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    depends_on:
      - postgres
    restart: always
    volumes:
      - superset_home:/app/superset_home
    networks:
      - guardian-net


volumes:
  postgres_data:
  superset_home:

networks:
  guardian-net:
    driver: bridge